default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reactchat/development.sqlite3

test:
  <<: *default
  database: reactchat/test.sqlite3

production:
  <<: *default
  database: reactchat/production.sqlite3
